'use strict';

module.exports = {
    WX_HEADER_CODE: 'X-WX-Code',
    WX_HEADER_ENCRYPTED_DATA: 'X-WX-Encrypted-Data',
    WX_HEADER_IV: 'X-WX-IV',
    WX_HEADER_ID: 'X-WX-Id',
    WX_HEADER_SKEY: 'X-WX-Skey',

    WX_SESSION_MAGIC_ID: 'F2C224D4-2BCE-4C64-AF9F-A6D872000D1A',

    ERR_LOGIN_FAILED: 'ERR_LOGIN_FAILED',
    ERR_INVALID_SESSION: 'ERR_INVALID_SESSION',
    ERR_CHECK_LOGIN_FAILED: 'ERR_CHECK_LOGIN_FAILED',

    INTERFACE_LOGIN: 'qcloud.cam.id_skey',
    INTERFACE_CHECK: 'qcloud.cam.auth',

    RETURN_CODE_SUCCESS: 0,
    RETURN_CODE_SKEY_EXPIRED: 60011,
    RETURN_CODE_WX_SESSION_FAILED: 60012,
};