'use strict';

module.exports = {
    WX_HEADER_CODE: 'X-WX-Code',
    WX_HEADER_ENCRYPT_DATA: 'X-WX-Encrypt-Data',
    WX_HEADER_ID: 'X-WX-Id',
    WX_HEADER_SKEY: 'X-WX-Skey',

    WX_SESSION_MAGIC_ID: 'F2C224D4-2BCE-4C64-AF9F-A6D872000D1A',

    ERR_LOGIN_FAILED: 'ERR_LOGIN_FAILED',
    ERR_SESSION_EXPIRED: 'ERR_SESSION_EXPIRED',
    ERR_CHECK_LOGIN_FAILED: 'ERR_CHECK_LOGIN_FAILED',

    INTERFACE_LOGIN: 'qcloud.cam.id_skey',
    INTERFACE_CHECK: 'qcloud.cam.auth',
};